import { recoveryExercise } from "@/domain/operations/recovery-evidence";
import { getWorkspaceShellContext } from "@/server/auth";
import { getOperationsPanel } from "@/server/operations-dashboard";
import { PageHeader, Panel } from "../ui";
import { operationsAction } from "./actions";
export default async function OperationsPage({searchParams}: {searchParams: Promise<{validation?: string;message?: string}>}) {
  const { workspaceContext: c } = await getWorkspaceShellContext();
  const [p, params] = await Promise.all([getOperationsPanel(c), searchParams]);
  const manage = c.role === "OWNER" || c.role === "ADMIN";
  const money = (v: unknown) => v === null || v === undefined ? "Unknown" : `$${Number(v).toFixed(4)}`;
  const paused = p.global.pausedAll || p.workspace.pausedAll;
  return <><PageHeader title="Operations" eyebrow="Internal pilot readiness" />
    {params.validation && <p role="alert">{params.validation}</p>}{params.message && <p role="status">{params.message}</p>}
    <Panel title="Automation health"><p><strong>{paused ? "AUTOMATION PAUSED" : "Review controls and gaps before running automation"}</strong></p><p>Active workflows: {p.usage.active} · Failed/unavailable runs: {String(p.health.failed)} · Budget-limited work: {String(p.health.budget_limited)}</p><p>Pending approvals: {String(p.health.pending_approvals)} · Verification failures: {String(p.health.verification_failures)} · Integrations needing attention: {String(p.health.reconnect)}</p><p>Production EXECUTE: DISABLED. QA EXECUTE: {p.readiness.qaExecute ? "SANDBOX ONLY" : "DISABLED"}. No customer CMS write adapter.</p></Panel>
    <Panel title="Pause controls">{(["PLATFORM","WORKSPACE"] as const).map(scope => { const state = scope === "PLATFORM" ? p.global : p.workspace; return <div key={scope}><h3>{scope === "PLATFORM" ? "Platform" : "Workspace"}</h3><p>All: {state.pausedAll ? "PAUSED" : "Eligible"} · Monitoring: {state.pausedMonitoring ? "PAUSED" : "Eligible"} · AI/PREPARE: {state.pausedAi ? "PAUSED" : "Eligible"} · Execution: {state.pausedExecution ? "PAUSED" : "Eligible (QA only)"}</p>{manage && (scope === "WORKSPACE" || p.platformOperator) && <form action={operationsAction} className="mx-form-grid"><input type="hidden" name="action" value="pause"/><input type="hidden" name="scope" value={scope}/><label>Category<select name="category"><option value="all">All automation</option><option value="monitoring">Scheduled monitoring and audits</option><option value="ai">AI / PREPARE / Visibility</option><option value="execution">External execution</option></select></label><label>Change<select name="paused"><option value="true">Pause</option><option value="false">Resume eligible future work</option></select></label><label>Reason<input name="reason" required maxLength={500}/></label><button className="mx-btn">Update {scope.toLowerCase()} pause</button></form>}</div>; })}<p>Existing evidence and read-only access remain available. Pauses are checked again before material steps. Resuming never retries an indeterminate paid call.</p></Panel>
    <Panel title="Workspace budgets"><p>Monthly committed/reserved ceiling usage: {money(p.usage.committedCostUsd)} / {money(p.workspace.monthlyCostUsd)}. Reservations are ceilings, not measured charges.</p><p>AI calls / reservations: {p.usage.aiCalls} / {p.workspace.aiCallLimit} · Visibility calls / reservations: {p.usage.visibilityCalls} / {p.workspace.visibilityCallLimit} · Crawl/monitor slots: {p.usage.crawls} / {p.workspace.crawlConcurrency}</p>{manage && <form action={operationsAction} className="mx-form-grid"><input type="hidden" name="action" value="budgets"/>{([{key:"monthlyCostUsd",label:"Monthly provider-cost ceiling (USD)",max:10000,step:"0.01"},{key:"activeWorkflowLimit",label:"Active workflow ceiling",max:20},{key:"aiCallLimit",label:"Monthly AI-call ceiling",max:10000},{key:"visibilityCallLimit",label:"Monthly visibility-call ceiling",max:10000},{key:"crawlConcurrency",label:"Crawl/monitor concurrency",max:5}] as const).map(f=><label key={f.key}>{f.label}<input name={f.key} type="number" min={0} max={f.max} step={"step" in f ? f.step : "1"} defaultValue={p.workspace[f.key]} required/></label>)}<label>Budget-change reason<input name="reason" required maxLength={500}/></label><button className="mx-btn">Save workspace budgets</button></form>}<p>New costly work defaults to a $0 ceiling. Internal usage accounting is separate from service-plan pricing and customer billing.</p></Panel>
    <Panel title="Usage ledger this month"><p>Known actual cost: {money(p.costs.reduce((sum,r)=>sum+Number(r.actual ?? 0),0))}. Unknown cost entries: {p.costs.reduce((sum,r)=>sum+Number(r.unknown),0)}. Unknown/unreported costs are not treated as free.</p>{p.costs.length ? <div style={{overflowX:"auto"}}><table><caption>Provider, run type and client usage (USD)</caption><thead><tr>{["Provider","Type","Client ID","Runs","Calls","Actual","Estimated","Unknown costs / calls"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{p.costs.map((r,i)=><tr key={i}><td>{String(r.provider)}</td><td>{String(r.category)}</td><td>{String(r.client_id ?? "Workspace")}</td><td>{String(r.runs)}</td><td>{String(r.calls)}</td><td>{money(r.actual)}</td><td>{money(r.estimated)}</td><td>{String(r.unknown)} / {String(r.unknown_calls)}</td></tr>)}</tbody></table></div>:<p>No measured runs this month.</p>}</Panel>
    <Panel title="Retention cleanup"><p>Raw AI Visibility captures expire after 90 days. Batches delete at most 100 expired captures; normalized observations, hashes, reports, approvals, execution and verification history remain.</p><p>Last cleanup: {p.cleanup ? `${p.cleanup.status} at ${p.cleanup.completedAt.toISOString()} — ${p.cleanup.deletedCount} deleted${p.cleanup.dryRun ? " (dry run)" : ""}` : "Not yet recorded"}. Cleanup failures: {String(p.health.cleanup_failures)}. Latest successful deletion batch: {p.successfulCleanup?.completedAt.toISOString() ?? "Not yet recorded"}.</p>{manage && <form action={operationsAction}><input type="hidden" name="action" value="cleanup"/><label>Cleanup mode<select name="dryRun"><option value="true">Dry run / count</option><option value="false">Delete expired captures</option></select></label><button className="mx-btn">Run retention cleanup</button></form>}{p.readiness.qaEnvironment && c.role === "OWNER" && <form action={operationsAction} className="mx-form-grid"><input type="hidden" name="action" value="retention_fixture"/><label>QA website ID for retention exercise<input name="websiteId" required/></label><button className="mx-btn">Create synthetic retention captures</button><p>QA only: creates one expired and one current test capture. No provider call, cost or API cadence.</p></form>}</Panel>
    <Panel title="Workspace export"><p>Owner-only JSON snapshot with entity counts, timestamp and version. Bounded to 1,000 records per entity and 10 MiB. Credentials, auth sessions and raw captures are excluded.</p>{c.role === "OWNER" && <a className="mx-btn" href="/api/workspace-export">Download workspace JSON</a>}</Panel>
    <Panel title="Recovery"><p>Retry creates a new policy-checked attempt for failed deterministic PREPARE, public website monitoring or read-only verification. Paid, active and execution jobs require manual review.</p>{p.jobs.map(r=><article key={String(r.id)}><p><a href={r.kind === "prepare" ? `/runs/${r.id}` : "/monitoring"}>{String(r.type)} · {String(r.status)} · {String(r.id)}</a></p>{manage && <form action={operationsAction} className="mx-form-grid"><input type="hidden" name="action" value="recovery"/><input type="hidden" name="id" value={String(r.id)}/><input type="hidden" name="kind" value={r.type === "verification" ? "verification" : String(r.kind)}/><label>Recovery action<select name="mode"><option value="review">Mark for manual review</option><option value="retry">Retry eligible failed internal run</option></select></label><label>Recovery reason<input name="reason" required maxLength={500}/></label><button className="mx-btn">Apply recovery</button></form>}</article>)}</Panel>
    <Panel title="Environment readiness"><dl>{Object.entries(p.readiness).map(([key,ready])=><div key={key}><dt>{key}</dt><dd>{key === "productionExecute" ? "DISABLED" : ready ? "Configured / enabled" : "Not configured / disabled"}</dd></div>)}</dl><p>Perplexity: {p.readiness.perplexity ? "Configured" : "Provider not configured"}. Search Console activation is optional. No credentials or billing are created by this page.</p><p>Operational schema 0017 is readable. Raw evidence and immutable generated records are currently DB-backed; private Blob is {p.readiness.blob ? "configured, migration not enabled" : "not configured"}. Backup/PITR window requires operator confirmation. Recovery exercise: {recoveryExercise.result} at {recoveryExercise.performedAt}; {recoveryExercise.scope}. {recoveryExercise.limitation}. See the Phase 10 recovery runbook.</p></Panel>
    <Panel title="Recent activity"><ul>{p.events.map(e=><li key={e.id}>{e.createdAt.toISOString()} · {e.action} · actor {e.actorUserId ?? e.actorType}</li>)}</ul></Panel>
  </>;
}
