import {expect,test,type Page,type Locator} from "@playwright/test";
async function action(page:Page,button:Locator){const path=new URL(page.url()).pathname;const [response]=await Promise.all([page.waitForResponse(r=>r.request().method()==="POST"&&new URL(r.url()).pathname===path,{timeout:90000}),button.click()]);expect(response.status()).toBeLessThan(400);}
async function fixturePackage(page:Page,mode:string){
 await page.goto("/qa-execution");await page.getByLabel("QA scenario").selectOption(mode);await action(page,page.getByRole("button",{name:"Create QA fixture"}));
 const fixture=page.getByTestId("qa-fixture").first();await expect(fixture).toContainText(mode);const target=await fixture.getByRole("link",{name:"Public fixture"}).getAttribute("href");
 await fixture.getByRole("link",{name:"Audit and prepare fixture"}).click();const websiteUrl=page.url();
 await page.getByRole("button",{name:"Start audit"}).click();await page.getByRole("button",{name:"Finalize audit snapshot"}).click();
 await page.goto("/opportunities?websiteId="+new URL(websiteUrl).pathname.split("/").pop());
 // The newest dedicated fixture has its own client/site and genuine public audit evidence.
 const matching=page.locator("main a.mx-row").filter({hasText:"seo.title"}).first();await matching.click();
 await action(page,page.getByRole("button",{name:"Prepare Page Optimization"}));
 await expect.poll(async()=>{await page.reload({waitUntil:"domcontentloaded"});return page.getByRole("link",{name:"Review draft",exact:true}).count()},{timeout:120000,intervals:[2000,4000]}).toBe(1);
 await page.getByRole("link",{name:"Review draft",exact:true}).click();const draft=page.url();
 await page.getByRole("link",{name:"Approval",exact:true}).click();await page.getByLabel("Decision").selectOption("APPROVED_UNCHANGED");await page.getByLabel("Comments").fill("Exact QA metadata proposal; this artifact approval does not authorize execution.");await action(page,page.getByRole("button",{name:"Record human decision"}));await expect(page.getByText("APPROVED",{exact:true})).toBeVisible();
 await page.goto(draft);await page.getByRole("button",{name:"Create implementation package"}).click();await expect(page.getByRole("heading",{name:"Implementation Package",exact:true})).toBeVisible();await expect(page.locator("main")).toContainText(target!);
 await page.getByRole("button",{name:"Request QA Execution"}).click();await expect(page).toHaveURL(/qa-execution/);
 const approval=page.getByTestId("execution-approval").first();await expect(approval).toContainText("PENDING");await expect(approval).toContainText("Independent verification required");await action(page,approval.getByRole("button",{name:"Approve QA Execution"}));await expect(approval).toContainText("APPROVED");
 const approvalId=await approval.locator('input[name="approvalId"]').first().inputValue();return {target,approvalId,websiteUrl};
}
async function execute(page:Page,approvalId:string){const box=page.getByTestId("execution-approval").filter({has:page.locator('input[name="approvalId"][value="'+approvalId+'"]')});await action(page,box.getByRole("button",{name:"Execute QA Change"}));await expect(page).toHaveURL(/executions\/[a-f0-9-]+$/);return page.url();}
async function state(page:Page,status:string){await expect.poll(async()=>{await page.reload({waitUntil:"domcontentloaded"});return page.getByTestId("execution-status").textContent()},{timeout:150000,intervals:[2000,4000]}).toBe("APPLY: "+status);}
test("Phase 8 QA-only approved execution, idempotency, independent verification and rollback",async({page,request})=>{
 test.setTimeout(900000);const id=Date.now()+"-"+Math.random().toString(36).slice(2,8);const email="optiq-phase8-"+id+"@example.com";const password="Phase8-"+id+"!";
 await page.goto("/login");await page.getByRole("button",{name:"Create account"}).click();await page.getByLabel("Name").fill("QA Sandbox Operator");await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Enter"}).click();await expect(page).toHaveURL(/workspace-setup/);await page.getByLabel("Workspace name").fill("Phase 8 QA "+id);await page.getByRole("button",{name:"Create workspace"}).click();
 await page.goto("/qa-execution");await expect(page.locator("main")).toContainText("Workspace execution: DISABLED");await action(page,page.getByRole("button",{name:"Enable Workspace execution",exact:true}));await expect(page.getByRole("button",{name:"Pause Workspace execution"})).toBeVisible();await action(page,page.getByRole("button",{name:"Enable QA metadata action",exact:true}));await expect(page.getByRole("button",{name:"Pause QA metadata action"})).toBeVisible();
 const good=await fixturePackage(page,"NONE");const execution=await execute(page,good.approvalId);
 if(process.env.OPTIQ_E2E_QA_EXECUTE_OFF === "true"){await state(page,"BLOCKED");await expect(page.locator("main")).toContainText("Platform QA execution is disabled");expect(await (await request.get(good.target!)).text()).toContain("<title>Home</title>");return;}
 await state(page,"VERIFIED");await expect(page.locator("main")).toContainText("public-html-verifier-v1.0");await expect(page.locator("main")).toContainText("observed");
 expect(await (await request.get(good.target!)).text()).toContain("QA metadata testing | OPTIQ QA Sandbox");
 await page.goto("/qa-execution");await expect(page.getByTestId("qa-fixture").first()).toContainText("Mutations 1");expect(await execute(page,good.approvalId)).toBe(execution);await state(page,"VERIFIED");
 await action(page,page.getByRole("button",{name:"Rollback QA Change"}));await expect.poll(async()=>{await page.reload({waitUntil:"domcontentloaded"});return page.getByTestId("execution-status").textContent()},{timeout:120000,intervals:[3000]}).toBe("ROLLBACK: ROLLED_BACK");await expect(page.locator("main")).toContainText("Verification: VERIFIED");
 const failed=await fixturePackage(page,"TITLE_MISMATCH");const failedUrl=await execute(page,failed.approvalId);await state(page,"FAILED");await expect.poll(async()=>{await page.reload({waitUntil:"domcontentloaded"});return page.getByRole("link",{name:"ROLLBACK: ROLLED_BACK ? Verification VERIFIED"}).count()},{timeout:120000,intervals:[3000]}).toBe(1);
 expect(await (await request.get(failed.target!)).text()).toContain("<title>Home</title>");await expect(page.locator("main")).toContainText("VERIFICATION_FAILED");await page.getByRole("link",{name:"ROLLBACK: ROLLED_BACK ? Verification VERIFIED"}).click();await expect(page.locator("main")).toContainText("Verification: VERIFIED");await page.getByRole("link",{name:"Original execution"}).click();expect(page.url()).toBe(failedUrl);await expect(page.getByTestId("execution-status")).toHaveText("APPLY: FAILED");
 await page.setViewportSize({width:390,height:844});await page.goto("/qa-execution");await expect(page.getByRole("navigation",{name:"Main navigation"})).toBeVisible();await expect(page.getByTestId("qa-fixture").first()).toContainText("Mutations 2");
 await page.getByRole("button",{name:"Sign out"}).click();await expect(page).toHaveURL(/login/);await page.getByRole("button",{name:"Sign in",exact:true}).click();await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Enter"}).click();await expect(page).not.toHaveURL(/login/);await page.goto(execution);await expect(page.getByTestId("execution-status")).toHaveText("APPLY: VERIFIED");
});
